name: cryptocoins_icons
description: Cryptocoins Icons by AllienWorks for Flutter
version: 0.1.0
author: James Naylor
homepage: www.github.com/euronay/cryptocoins-icons-flutter

dependencies:
  flutter:
    sdk: flutter

flutter:
  fonts:
    - family: CryptoCoins
      fonts:
        - asset: webfont/cryptocoins.ttf
